plugins {
    id 'com.gtnewhorizons.gtnhconvention'
}

tasks.withType(Javadoc) {
    options.addStringOption('Xdoclint:none', '-quiet')

    options.links = [
            "https://skmedix.github.io/ForgeJavaDocs/javadoc/forge/1.7.10-10.13.4.1614/",
            "https://kamkeel.github.io/CustomNPC-Plus/"
    ]

    options.memberLevel = JavadocMemberLevel.PUBLIC
    options.showFromPublic()

    options.encoding = 'UTF-8'
    options.charSet = 'UTF-8'

    failOnError = false
}